### ISSUE TITLE
Code Readability & Flow

### ISSUE THREAD

**Issue by AlexZorzi** [Catta1997/animesaturn-downloader#5]
Secondo me, negli ultimi commits del "beta" branch il codice è diventato più difficile da leggere.
sono state divise le Funzioni (ma non tutte) e le variabili, quindi avendo un impostazione come "classe" ma senza i vantaggi di avere una vera e propria classe.
non ho mai incontrato personalmente un codice con questo tipo di "flow" ma mi sembra più macchinoso che altro, io proporrei un vero e proprio uso di classi.
provero nel frattempo a fare un refractor del codice usando le classi, per poi proporlo come PR
@Catta1997

**Comment by Catta1997** [comment]
ho diviso le  funzioni usate da entrambe in un file  saporato, in modo da poterle modificare solo una volta. Le variabili ho dovuto metterle in un altro file ancora perché  tutti e tre i file devono poter accedere a quelle variabili. Per ora ho fatto così perché non conosco bene l'uso delle classi in python

**Comment by AlexZorzi** [comment]
#6

**Comment by AlexZorzi** [comment]
Close #6
